In [1]:
import pandas as pd

subway_df = pd.read_csv("results/지하철_위도경도.csv")
subway_df

       전철역명       호선                    주소         위도          경도     구
0        석계      1호선        서울 노원구 화랑로 341  37.615306  127.065647   노원구
1        서울      1호선       서울 중구 세종대로 지하 2  37.557159  126.972555    중구
2       영등포      1호선     서울 영등포구 여의대방로 300  37.513325  126.926303  영등포구
3        대방      1호선     서울 영등포구 여의대방로 300  37.513325  126.926303  영등포구
4       신도림      1호선  서울 구로구 새말로 지하 117-21  37.508770  126.891081   구로구
..      ...      ...                   ...        ...         ...   ...
401      정릉  우이신설경전철     서울 성북구 보국문로 지하 88  37.612146  127.008208   성북구
402  북한산보국문  우이신설경전철     서울 성북구 보국문로 지하 88  37.612146  127.008208   성북구
403     신설동  우이신설경전철    서울 성북구 동소문로 지하 102  37.592718  127.016478   성북구
404      보문  우이신설경전철    서울 성북구 아리랑로 지하 122  37.602688  127.013496   성북구
405    솔밭공원  우이신설경전철        서울 강북구 삼양로 595  37.656155  127.013092   강북구

[406 rows x 6 columns]

In [3]:
new_df = subway_df.groupby('구').size().reset_index(name='역의 개수')
new_df.set_index('구', inplace=True)

new_df.to_csv("results/지하철 역 개수.csv")

new_df

      역의 개수
구
강남구      37
강동구      14
강북구       9
강서구      24
관악구       8
광진구      12
구로구      13
금천구       4
노원구      16
도봉구       9
동대문구     16
동작구      23
마포구      22
서대문구      7
서초구      19
성동구      21
성북구      15
송파구      28
양천구       6
영등포구     20
용산구      18
은평구      14
종로구      13
중구       22
중랑구      16